[tool.poetry]
name = "golchemy"
version = "0.1.0"
description = ""
authors = [
    "Mitchell Riley <mitchell.v.riley@gmail.com>"
]

license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
python-lifelib = { path = "./python-lifelib/", develop = true }
toml = "^0.10.2"

