[bblocks]
rle = "21b2o$21b2o7$8b2o$8b2o3$2o$2o!"

[bfirstblocks]
rle = "13b2o$13b2o7$2o$2o!"

[bdebris]
rle = "32b2o$32b2o$b2o$obo$2o4$19b2o$19b2o3$11b2o$11b2o!"

[herschelblocks]
rle = "8b2o$8b2o3$2o$2o!"

[herscheldebris]
rle = "b2o$obo$2o4$19b2o$19b2o3$11b2o$11b2o!"

[blockade]
rle = "8b2o$4b2o2b2o$4b2o18$4b2o$2o2b2o$2o!"

[biblock]
rle = "2ob2o$2ob2o!"

[blocks_4_0]
rle = "2o2b2o$2o2b2o!"

[blocks_5_0]
rle = "2o3b2o$2o3b2o!"

[blocks_6_0]
rle = "2o4b2o$2o4b2o!"

[blocks_7_0]
rle = "2o5b2o$2o5b2o!"

[blocks_8_0]
rle = "2o6b2o$2o6b2o!"

[blocks_9_0]
rle = "2o7b2o$2o7b2o!"

[blocks_10_0]
rle = "2o8b2o$2o8b2o!"


[blocks_4_1]
rle = "2o$2o2b2o$4b2o!"
[blocks_5_1]
rle = "2o$2o3b2o$5b2o!"
[blocks_6_1]
rle = "2o$2o4b2o$6b2o!"
[blocks_7_1]
rle = "2o$2o5b2o$7b2o!"
[blocks_8_1]
rle = "2o$2o6b2o$8b2o!"
[blocks_9_1]
rle = "2o$2o7b2o$9b2o!"
[blocks_10_1]
rle = "2o$2o8b2o$10b2o!"













